# Generated by Django 3.0.2 on 2020-08-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='conversations',
            field=models.ManyToManyField(blank=True, to='chat.ConversationModel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.MessageModel'),
        ),
    ]
